
% This Matlab script performs a comparison between GFM and GFL BESS Controllers 
% with varying level of grid strength (SCR) and PV penetration levels.
% Copyright 2022 - 2023 The MathWorks, Inc.

% Simulating strong grid conditions by reducing feeder impedance and PV penetration 
% level.
SimulationTime=3.5;
Line.l_km=5;                  %Line length 0.5 km for strong grid
Feeder.lengthFirstHalf=0.05;  %Feeder length in Km for strong grid
Feeder.lengthSecondHalf=0.1;  %Feeder length in Km for strong grid
Array.insolation=200;         %Solar Insolation
PVpower=20e6;                 %Power generated by PV plant in (Watts)
GridStrength=1;               %Strong Grid
%Simulating Load change event
Load2CB_initial=0;            %Load CB switching condition
Load2CB_final=1;              %Load CB switching condition
%Load connected to SM
SM.P_load=1e6;                %Load connected to SM
SM.Q_load=1e3;                %Load connected to SM
SCRCal1= BatteryStoragePVPlantGFMSCRCal(Line,Feeder,Grid,SubTransmissionLine,PVpower);
Scenario.number=2;    % Load chage event is selected
Scenario.t_event=2.5; % Time at which event is triggered
[Parameters] =BatteryStoragePVPlantGFMSettingScenario(Scenario.number,SimulationTime,Scenario.t_event); % Scenario settings
%Secnerio Parameters
Scenario.Fault_distance=Parameters(1);Scenario.Fault_time=Parameters(2);
Scenario.Fault_duration=Parameters(3);Scenario.Load_switching_time=Parameters(4);
Scenario.Solar_flactuation_time=Parameters(5);Scenario.Grid_outage_time=Parameters(6);
Scenario.Line_trip_time=Parameters(7);
BESSControl=2;                      % BESS control grid following voltage and frequency support 
sim('BatteryStoragePVPlantGFM.slx') % Simulate 
SimlogCompare1=logs_ee_spv_park_battery;
if BESSControl==1
    Control='BESS Controller: Grid Forming VSM';
else
    Control='BESS Controller: Grid Following V & F Support';
end
disp(Control)
disp(['Calculated SCR at POI: ',num2str(SCRCal1.SCR)]);
figure;
BatteryStoragePVPlantGFMplotCurve_voltage_frequency(SimlogCompare1,Scenario.number,SimulationTime)  %Plot results
%% 
% Simulating weak grid conditions by reducing feeder impedance and PV penetration 
% level.

Line.l_km=5;                   %Line length in Km for weak grid
Feeder.lengthFirstHalf=0.05;   %Feeder length in Km for weak grid
Feeder.lengthSecondHalf=0.6;   %Feeder length in Km for weak grid
Array.insolation=800;          %Solar Insolation
PVpower=80e6;                  %Power generated by PV plant
GridStrength=0 ;               %Weak Grid
SCRCal3= BatteryStoragePVPlantGFMSCRCal(Line,Feeder,Grid,SubTransmissionLine,PVpower);
BESSControl=2;                 % BESS control grid following voltage and frequency support
%Load connected to SM
SM.P_load=70e6;
SM.Q_load=10e3;
if BESSControl==1
    Control='BESS Controller: Grid Forming VSM';
else
    Control='BESS Controller: Grid Following V & F Support';
end
sim('BatteryStoragePVPlantGFM.slx') % Simulate 
disp(Control)
SimlogCompare12=logs_ee_spv_park_battery;
disp(['Calculated SCR at POI: ',num2str(SCRCal3.SCR)]);
figure;
BatteryStoragePVPlantGFMplotCurve_voltage_frequency(SimlogCompare12,Scenario.number,SimulationTime) %Plot results
BESSControl=1;             % BESS control grid forming VSM
if BESSControl==1
    Control='BESS Controller: Grid Forming VSM';
else
    Control='BESS Controller: Grid Following V & F Support';
end
sim('BatteryStoragePVPlantGFM.slx') %Simulate
SimlogCompare11=logs_ee_spv_park_battery;
disp(Control)
figure;
BatteryStoragePVPlantGFMplotCurve_voltage_frequency(SimlogCompare11,Scenario.number,SimulationTime)  %Plot results